# this file is used by pyannote.metrics and pyannote.database
# $ export PYANNOTE_DATABASE_CONFIG=/path/to/this/database.yml
# $ pyannote-metrics.py diarization --subset=development BabyTrain.SpeakerDiarization.All /path/to/one/run/to/rule/them/all.rttm

Protocols:

   CHiME5:
      SpeakerDiarization:
         # CHiME5.SpeakerDiarization.U01
         U01:
           train:
             annotation: /export/fs01/jsalt19/databases/CHiME5/train/allU01_train.rttm
             annotated: /export/fs01/jsalt19/databases/CHiME5/train/allU01_train.uem
           development:
             annotation: /export/b01/leibny/jsalt-2020/jsalt2019-diadet/egs/jsalt2019-diadet/v5/rttms_desh_2/rttm_dev_final_U01.rttm
             annotated: /export/b01/leibny/jsalt-2020/jsalt2019-diadet/egs/jsalt2019-diadet/v5/rttms_desh_2/allU01_dev.uem
           test:
             annotation: /export/b01/leibny/jsalt-2020/jsalt2019-diadet/egs/jsalt2019-diadet/v5/rttms_desh_2/rttm_eval_final_U01.rttm
             annotated: /export/b01/leibny/jsalt-2020/jsalt2019-diadet/egs/jsalt2019-diadet/v5/rttms_desh_2/allU01_test.uem


   DIHARD_dev:
      SpeakerDiarization:
         All:
           #train:
           #  annotation: /export/fs01/jsalt19/databases/AMI/train/allArray1-01_train.rttm
           #  annotated: /export/fs01/jsalt19/databases/AMI/train/allArray1-01_train.uem
           development:
             annotation: /export/b04/leibny/jsalt-dihard-May2020/dihard-jsalt/egs/jsalt2019-diadet/v5/databases/DIHARD/dev/all.rttm
             annotated: /export/b04/leibny/jsalt-dihard-May2020/dihard-jsalt/egs/jsalt2019-diadet/v5/databases/DIHARD/dev/all.uem
           #test:
           #  annotation: /export/b01/leibny/jsalt-2020/jsalt2019-diadet/egs/jsalt2019-diadet/v5/databases/AMI/test/allArray1-01_test.rttm
           #  annotated: /export/b01/leibny/jsalt-2020/jsalt2019-diadet/egs/jsalt2019-diadet/v5/databases/AMI/test/allArray1-01_test.uem
          
         # Dihard.SpeakerDiarization_eval
   DIHARD_eval:
      SpeakerDiarization:
         All:
           #train:
           #  annotation: /export/fs01/jsalt19/databases/AMI/train/allArray1-01_train.rttm
           #  annotated: /export/fs01/jsalt19/databases/AMI/train/allArray1-01_train.uem
           #development:
           #  annotation: /export/b01/leibny/jsalt-2020/jsalt2019-diadet/egs/jsalt2019-diadet/v5/databases/AMI/dev/allArray1-01_dev.rttm
           #  annotated: /export/b01/leibny/jsalt-2020/jsalt2019-diadet/egs/jsalt2019-diadet/v5/databases/AMI/dev/allArray1-01_dev.uem
           test:
             annotation: /export/b04/leibny/jsalt-dihard-May2020/dihard-jsalt/egs/jsalt2019-diadet/v5/databases/DIHARD/eval/all.rttm
             annotated: /export/b04/leibny/jsalt-dihard-May2020/dihard-jsalt/egs/jsalt2019-diadet/v5/databases/DIHARD/eval/all.uem
             #annotation: /export/b04/leibny/jsalt-dihard-May2020/dihard-jsalt/egs/jsalt2019-diadet/v5/databases/DIHARD/eval/all-43-0113-0191.rttm
             #annotated: /export/b04/leibny/jsalt-dihard-May2020/dihard-jsalt/egs/jsalt2019-diadet/v5/databases/DIHARD/eval/all-43-0113-0191.uem
          
Databases:
          
Databases:

   CHiME5: /export/fs01/jsalt19/databases/CHiME5/*/wav/{uri}.wav
   #AMI: /export/corpora4/ami/amicorpus/*/audio/{uri}.wav
   #Dihard: /export/corpora/LDC/LDC2019E3*/LDC2019E31_Second_DIHARD_Challenge_Development_Data/data/single_channel/flac/{uri}.flac 
   AMI: /export/corpora4/ami/amicorpus/*/audio/{uri}.wav
   DIHARD_dev: /export/corpora/LDC/LDC2019E31/LDC2019E31_Second_DIHARD_Challenge_Development_Data/data/single_channel/flac/{uri}.flac 
   #DIHARD_eval: /export/corpora/LDC/LDC2019E32/LDC2019E32_Second_DIHARD_Challenge_Evaluation_Data_V1.1/data/single_channel/flac/{uri}.flac 
   DIHARD_eval: /export/b04/leibny/jsalt-dihard-May2020/dihard-jsalt/egs/jsalt2019-diadet/v5/data/{uri}.wav 
